name: Reusable Build

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input message
        uses: actions/Checkout@v3
      - name: Run shell script
        run: bash ./test.sh "${{inputs.message}}"
        # run: echo "Reusable workflow says:${{ inputs.message }}"
