name: Reusable Build

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: message
      - run: echo "Reusable workflow says: ${{ inputs.message }}"
