name: Reusable Build

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: sdlc-org/CI-Template
          ref: main
      - name: pwd dir
        run: pwd
        
      - name: List files in repo
        run: ls -alh 

      - name: Run shell script
        run: bash ./test.sh "${{ inputs.message }}"

        # run: echo "Reusable workflow says:${{ inputs.message }}"
